services:
  - type: web
    name: cardiolink-backend
    env: python
    pythonVersion: 3.10
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
